FROM java:8
EXPOSE 8080 5051
RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list

RUN apt-get -o Acquire::Check-Valid-Until=false update

RUN apt-get install -y maven

RUN ls -l

WORKDIR /code

ADD ./pom.xml /code/pom.xml

ADD ./src /code/src
CMD ["mvn", "-Dexec.mainClass=com.mera.education.grpc.task.Application", "exec:java"]
